### ISSUE TITLE
Stuck on Saving artifacts...  after successful migrations

### ISSUE THREAD

**Issue by thcrnk** [rhlsthrm/truffle-hdwallet-provider-privkey#3]
Hi,

Using this provider with Truffle got me stuck on "Saving artifacts..." after migrations. 
Here is my truffle.js config for Ropsten.
```
		ropsten: {
			provider: function () {
				return new HDWalletProvider(privateKey, infuraRopsten)
			},
			network_id: 3,
			gas: 4000000,
			gasPrice: 20000000000
		}
```

And here is the output and the migration is stuck after saving artifacts:
```
  ContractTest: 0x9d8289e252385c02d099487f2dd209e804c3abd5
Saving successful migration to network...
  ... 0x49b7b8b55ed72ce0bdbc580e35961364ff178b5f94889f8eef51f97a92e17d2d
Saving artifacts...
```

Everything else is perfect with the migration, all contract addresses and transaction hashes are correct.

```
Versions:
Truffle v4.1.0 (core: 4.1.0)
Solidity v0.4.19 (solc-js)
```

Do you have same problem using it with Truffle?

**Comment by rhlsthrm** [comment]
Does it work properly without the provider?

**Comment by thcrnk** [comment]
Yes, migrating on ganache/testrpc without provider is working fine. And migrating to ropsten with the old provider(with mnemonic) also working as expected.

**Comment by RomanFro** [comment]
Have you resolved this issue?

**Comment by thcrnk** [comment]
Nope, currently still killing the process after all contracts are deployed otherwise, it is stuck

**Comment by RomanFro** [comment]
Yep, `process.exit(0)` in the end of migration script fixed it for me.

**Comment by jeffzwang** [comment]
I am also getting this issue :(

**Comment by etdej** [comment]
Same issue here

**Comment by rhlsthrm** [comment]
I have had this same issue for a while. The process seems to hang on deploying to Rinkeby/Mainnet. However, the contracts deploy successfully. I haven't tried @RomanFro's workaround yet. If anyone has another solution that can be integrated into this repo, please feel free to PR.

**Comment by TitBourne** [comment]
same issue here

**Comment by cdljsj** [comment]
Hanging for me even on "truffle compile", everything works well without the provider

**Comment by AlexYenkalov** [comment]
"truffle-hdwallet-provider": "0.0.3" - :) works well
"truffle-hdwallet-provider": "0.0.5" - :( stucks

**Comment by nambrot** [comment]
Same problem!

**Comment by nambrot** [comment]
https://github.com/trufflesuite/truffle-migrate/issues/14#issuecomment-334445080 solved it for me

**Comment by ngotiendatdinosys** [comment]
Same problem!

**Comment by rhlsthrm** [comment]
If you guys upgrade to the web3 1.0 version it shouldn't have this issue anymore.
