### ISSUE TITLE
PK returning wrong address

### ISSUE THREAD

**Issue by KPontes** [rhlsthrm/truffle-hdwallet-provider-privkey#8]
Hi, I have a privkey for an existing address on Rinkeby network: "0x85Be6c1f4DE7a2D1de9564086394700ccb7d0852".
But when I call myContract.myMethod.send I'm receiving an Error: Unknown address - unable to sign transaction for this address: "0x85be6c1f4de7a2d1de9564086394700ccb7d0852"
Actually the component is lowercasing all the uppercase chars from my address.
Am I doing something wrong, or is there some solution?

Thank you,
Krishnan

**Comment by rhlsthrm** [comment]
Are you using this provider? The new Web3 1.0.0 returns mixed case addresses, while the old one (what this provider uses) uses the old Web3 (0.2x.x). If you're using web3 1.0.0 you don't need this package. There is a function that can use your private key to get an account object directly: https://web3js.readthedocs.io/en/1.0/web3-eth-accounts.html#privatekeytoaccount

**Comment by KPontes** [comment]
Thank you, it worked
